Repository Azure/azure-event-hubs-spark, pull requests merged in 2018-08, with the labels that each got.

#368 Change the ehClient to a lazy variable
  core/src/main/scala/org/apache/spark/sql/eventhubs/EventHubsSource.scala
Labels: enhancement

#373 Handle DescribedType in properties
  core/src/main/scala/org/apache/spark/sql/eventhubs/EventHubsRelation.scala
  core/src/main/scala/org/apache/spark/sql/eventhubs/EventHubsSource.scala
  core/src/test/scala/org/apache/spark/sql/eventhubs/EventHubsRelationSuite.scala
  core/src/test/scala/org/apache/spark/sql/eventhubs/EventHubsSourceSuite.scala
Labels: bug fix

#369 In translate, redo receive when it returns null
  core/src/main/scala/org/apache/spark/eventhubs/EventHubsConf.scala
  core/src/main/scala/org/apache/spark/eventhubs/client/CachedEventHubsReceiver.scala
  core/src/main/scala/org/apache/spark/eventhubs/client/EventHubsClient.scala
  core/src/main/scala/org/apache/spark/eventhubs/utils/RetryUtils.scala
  core/src/main/scala/org/apache/spark/sql/eventhubs/EventHubsForeachWriter.scala
Labels: bug fix

#377 Cached receivers are async
  FAQ.md
  README.md
  core/src/main/scala/org/apache/spark/eventhubs/client/CachedEventHubsReceiver.scala
  core/src/main/scala/org/apache/spark/eventhubs/rdd/EventHubsRDD.scala
  core/src/main/scala/org/apache/spark/eventhubs/utils/SimulatedCachedReceiver.scala
  core/src/main/scala/org/apache/spark/eventhubs/utils/SimulatedEventHubs.scala
  core/src/test/scala/org/apache/spark/eventhubs/utils/EventHubsTestUtilsSuite.scala
Labels: enhancement

#375 Properties can be added in EventHubsSink
  core/src/main/scala/org/apache/spark/eventhubs/client/Client.scala
  core/src/main/scala/org/apache/spark/eventhubs/client/EventHubsClient.scala
  core/src/main/scala/org/apache/spark/eventhubs/utils/SimulatedClient.scala
  core/src/main/scala/org/apache/spark/eventhubs/utils/SimulatedEventHubs.scala
  core/src/main/scala/org/apache/spark/sql/eventhubs/EventHubsSink.scala
  core/src/main/scala/org/apache/spark/sql/eventhubs/EventHubsWriteTask.scala
  core/src/main/scala/org/apache/spark/sql/eventhubs/EventHubsWriter.scala
  core/src/test/scala/org/apache/spark/sql/eventhubs/EventHubsSinkSuite.scala
  docs/structured-streaming-eventhubs-integration.md
Labels: feature
